name: Build Windows EXE with Nuitka

on:
  workflow_dispatch:   # Trigger manually
  push:
    branches:
      - main           # Automatically runs on push to main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
        cache-dependency-path: |
            **/requirements*.txt

    - name: Install Nuitka + dependencies
      run: |
        pip install nuitka
        python -m pip install --upgrade pip setuptools wheel
        pip install python-socketio requests psutil pynput opencv-python mss numpy pyperclip

    - name: Build Executable
      uses: Nuitka/Nuitka-Action@main
      with:
          nuitka-version: main
          script-name: agent.py
          mode: onefile

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
              name: windows-latest Build
              path: |
                build/*.exe
                build/*.bin
                build/*.app/**/*
                build/*.dist/**/*
              include-hidden-files: true


