name: Build Windows EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          update-environment: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Cache Nuitka
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\AppData\Local\Nuitka\Nuitka\Cache
          key: nuitka-cache-${{ runner.os }}-${{ hashFiles('**/agent.py') }}
          restore-keys: |
            nuitka-cache-${{ runner.os }}-

      - name: Build EXE with Nuitka
        run: |
          python -m nuitka --onefile --windows-console-mode=disable --remove-output --lto=yes --assume-yes-for-downloads --jobs=4 --python-flag=-OO agent.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: agent.exe
