name: Build Windows EXE with Nuitka

on:
  workflow_dispatch:   # Trigger manually
  push:
    branches:
      - main           # Automatically runs on push to main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Nuitka + dependencies
      run: |
        pip install nuitka zstandard

    - name: Compile with Nuitka
      run: |
        python -m nuitka agent.py --onefile --python-flag=-OO --assume-yes-for-downloads --include-package=socketio --include-package=engineio --include-package=requests --include-package=psutil --include-package=pynput --include-package=cv2 --include-package=mss --include-package=numpy --include-package=pyperclip --include-package=uuid

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: agent.exe
